package com.marketour.domain;
// Generated 2/05/2015 08:24:36 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Alimentacion generated by hbm2java
 */
@Entity
@Table(name="Alimentacion"
    ,catalog="devfloor_marketour"
)
public class Alimentacion  implements java.io.Serializable {


     private int id;
     private Producto producto;
     private PlanAlimentacion planAlimentacion;

    public Alimentacion() {
    }

	
    public Alimentacion(Producto producto) {
        this.producto = producto;
    }
    public Alimentacion(Producto producto, PlanAlimentacion planAlimentacion) {
       this.producto = producto;
       this.planAlimentacion = planAlimentacion;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="producto"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="plan")
    public PlanAlimentacion getPlanAlimentacion() {
        return this.planAlimentacion;
    }
    
    public void setPlanAlimentacion(PlanAlimentacion planAlimentacion) {
        this.planAlimentacion = planAlimentacion;
    }




}


