package com.marketour.domain;
// Generated 21/04/2015 08:03:17 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name="Ciudad"
    ,catalog="devfloor_marketour"
)
public class Ciudad  implements java.io.Serializable {


     private Integer id;
     private Departamento departamento;
     private String descripcion;
     private String codigo;
     private String latitud;
     private String longitud;
     private int estado;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Ciudad() {
    }

	
    public Ciudad(Departamento departamento, String codigo, int estado) {
        this.departamento = departamento;
        this.codigo = codigo;
        this.estado = estado;
    }
    public Ciudad(Departamento departamento, String descripcion, String codigo, String latitud, String longitud, int estado, Set<Producto> productos) {
       this.departamento = departamento;
       this.descripcion = descripcion;
       this.codigo = codigo;
       this.latitud = latitud;
       this.longitud = longitud;
       this.estado = estado;
       this.productos = productos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(cascade = javax.persistence.CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinColumn(name="departamento", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="codigo", nullable=false, length=50)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="latitud", length=50)
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="longitud", length=50)
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

@OneToMany(cascade = javax.persistence.CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ciudad")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


