package com.marketour.domain;
// Generated 13/04/2015 12:03:59 AM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="Cliente"
    ,catalog="grupocre_marketour"
)
public class Cliente  implements java.io.Serializable {


     private int id;
     private String descripcion;

    public Cliente() {
    }

	
    public Cliente(int id) {
        this.id = id;
    }
    public Cliente(int id, String descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


