package com.marketour.domain;

// Generated 4/04/2015 03:32:21 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClienteCompra generated by hbm2java
 */
@Entity
@Table(name = "ClienteCompra", catalog = "grupocre_marketour")
public class ClienteCompra implements java.io.Serializable {

	private Integer id;
	private Integer idCliente;
	private Integer idCompra;

	public ClienteCompra() {
	}

	public ClienteCompra(Integer idCliente, Integer idCompra) {
		this.idCliente = idCliente;
		this.idCompra = idCompra;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "idCliente")
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "idCompra")
	public Integer getIdCompra() {
		return this.idCompra;
	}

	public void setIdCompra(Integer idCompra) {
		this.idCompra = idCompra;
	}

}
