package com.marketour.domain;
// Generated 21/04/2015 08:03:17 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="Cliente"
    ,catalog="devfloor_marketour"
)
public class Cliente  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String descripcion;
     private Set<MedioPago> medioPagos = new HashSet<MedioPago>(0);
     private Set<Compra> compras = new HashSet<Compra>(0);

    public Cliente() {
    }

	
    public Cliente(Usuario usuario) {
        this.usuario = usuario;
    }
    public Cliente(Usuario usuario, String descripcion, Set<MedioPago> medioPagos, Set<Compra> compras) {
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.medioPagos = medioPagos;
       this.compras = compras;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="usuario"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(cascade = javax.persistence.CascadeType.ALL, fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(cascade = javax.persistence.CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<MedioPago> getMedioPagos() {
        return this.medioPagos;
    }
    
    public void setMedioPagos(Set<MedioPago> medioPagos) {
        this.medioPagos = medioPagos;
    }

@OneToMany(cascade = javax.persistence.CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }




}


