package com.marketour.domain;

// Generated 7/04/2015 12:31:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name = "Compra", catalog = "grupocre_marketour")
public class Compra implements java.io.Serializable {

	private Integer id;
	private Date fecha;
	private Integer calificacion;
	private Integer estado;
	private Integer idMoneda;
	private Integer idFactura;
	private Integer idMedioPago;

	public Compra() {
	}

	public Compra(Date fecha, Integer calificacion, Integer estado,
			Integer idMoneda, Integer idFactura, Integer idMedioPago) {
		this.fecha = fecha;
		this.calificacion = calificacion;
		this.estado = estado;
		this.idMoneda = idMoneda;
		this.idFactura = idFactura;
		this.idMedioPago = idMedioPago;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "calificacion")
	public Integer getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Integer calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "idMoneda")
	public Integer getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(Integer idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "idFactura")
	public Integer getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	@Column(name = "idMedioPago")
	public Integer getIdMedioPago() {
		return this.idMedioPago;
	}

	public void setIdMedioPago(Integer idMedioPago) {
		this.idMedioPago = idMedioPago;
	}

}
