package com.marketour.domain;
// Generated 12/04/2015 01:17:24 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Disponibilidad generated by hbm2java
 */
@Entity
@Table(name="Disponibilidad"
    ,catalog="grupocre_marketour"
)
public class Disponibilidad  implements java.io.Serializable {


     private Integer id;
     private int producto;
     private Date fechaInicio;
     private Date fechaFin;
     private Integer personas;

    public Disponibilidad() {
    }

	
    public Disponibilidad(int producto) {
        this.producto = producto;
    }
    public Disponibilidad(int producto, Date fechaInicio, Date fechaFin, Integer personas) {
       this.producto = producto;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.personas = personas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="producto", nullable=false)
    public int getProducto() {
        return this.producto;
    }
    
    public void setProducto(int producto) {
        this.producto = producto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaInicio", length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaFin", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="personas")
    public Integer getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Integer personas) {
        this.personas = personas;
    }




}


