package com.marketour.domain;

// Generated 4/04/2015 03:32:21 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FacturaProducto generated by hbm2java
 */
@Entity
@Table(name = "FacturaProducto", catalog = "grupocre_marketour")
public class FacturaProducto implements java.io.Serializable {

	private Integer id;
	private Integer idFactura;
	private Integer idProducto;

	public FacturaProducto() {
	}

	public FacturaProducto(Integer idFactura, Integer idProducto) {
		this.idFactura = idFactura;
		this.idProducto = idProducto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "idFactura")
	public Integer getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	@Column(name = "idProducto")
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

}
