package com.marketour.domain;
// Generated 2/05/2015 08:24:36 PM by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FormaPago generated by hbm2java
 */
@Entity
@Table(name="FormaPago"
    ,catalog="devfloor_marketour"
)
public class FormaPago  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private BigDecimal recargo;
     private int estado;
     private Set<MedioPago> medioPagos = new HashSet<MedioPago>(0);

    public FormaPago() {
    }

	
    public FormaPago(int estado) {
        this.estado = estado;
    }
    public FormaPago(String descripcion, BigDecimal recargo, int estado, Set<MedioPago> medioPagos) {
       this.descripcion = descripcion;
       this.recargo = recargo;
       this.estado = estado;
       this.medioPagos = medioPagos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="recargo", precision=10)
    public BigDecimal getRecargo() {
        return this.recargo;
    }
    
    public void setRecargo(BigDecimal recargo) {
        this.recargo = recargo;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formaPago")
    public Set<MedioPago> getMedioPagos() {
        return this.medioPagos;
    }
    
    public void setMedioPagos(Set<MedioPago> medioPagos) {
        this.medioPagos = medioPagos;
    }




}


