package com.marketour.domain;
// Generated 13/04/2015 12:03:59 AM by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemCompra generated by hbm2java
 */
@Entity
@Table(name="ItemCompra"
    ,catalog="grupocre_marketour"
)
public class ItemCompra  implements java.io.Serializable {


     private Integer id;
     private Integer paquete;
     private Integer producto;
     private Integer compra;
     private BigDecimal valor;
     private Integer cantidad;

    public ItemCompra() {
    }

    public ItemCompra(Integer paquete, Integer producto, Integer compra, BigDecimal valor, Integer cantidad) {
       this.paquete = paquete;
       this.producto = producto;
       this.compra = compra;
       this.valor = valor;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="paquete")
    public Integer getPaquete() {
        return this.paquete;
    }
    
    public void setPaquete(Integer paquete) {
        this.paquete = paquete;
    }

    
    @Column(name="producto")
    public Integer getProducto() {
        return this.producto;
    }
    
    public void setProducto(Integer producto) {
        this.producto = producto;
    }

    
    @Column(name="compra")
    public Integer getCompra() {
        return this.compra;
    }
    
    public void setCompra(Integer compra) {
        this.compra = compra;
    }

    
    @Column(name="valor", precision=10)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


