package com.marketour.domain;
// Generated 12/04/2015 01:17:24 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MedioPago generated by hbm2java
 */
@Entity
@Table(name="MedioPago"
    ,catalog="grupocre_marketour"
)
public class MedioPago  implements java.io.Serializable {


     private Integer id;
     private Integer cliente;
     private Integer forma;
     private Integer estado;

    public MedioPago() {
    }

    public MedioPago(Integer cliente, Integer forma, Integer estado) {
       this.cliente = cliente;
       this.forma = forma;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="cliente")
    public Integer getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Integer cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="forma")
    public Integer getForma() {
        return this.forma;
    }
    
    public void setForma(Integer forma) {
        this.forma = forma;
    }

    
    @Column(name="estado")
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


