package com.marketour.domain;

// Generated 10/05/2015 02:54:41 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name = "Moneda", catalog = "devfloor_marketour")
public class Moneda implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private String signo;
	private BigDecimal conversion;
	private int estado;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Moneda() {
	}

	public Moneda(int estado) {
		this.estado = estado;
	}

	public Moneda(String descripcion, String signo, BigDecimal conversion,
			int estado, Set<Usuario> usuarios) {
		this.descripcion = descripcion;
		this.signo = signo;
		this.conversion = conversion;
		this.estado = estado;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "signo", length = 50)
	public String getSigno() {
		return this.signo;
	}

	public void setSigno(String signo) {
		this.signo = signo;
	}

	@Column(name = "conversion", precision = 10)
	public BigDecimal getConversion() {
		return this.conversion;
	}

	public void setConversion(BigDecimal conversion) {
		this.conversion = conversion;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moneda")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
