package com.marketour.domain;
// Generated 20/04/2015 12:40:07 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PaqueteProducto generated by hbm2java
 */
@Entity
@Table(name="PaqueteProducto"
    ,catalog="devfloor_marketour"
)
public class PaqueteProducto  implements java.io.Serializable {


     private Integer id;
     private Producto producto;
     private Paquete paquete;

    public PaqueteProducto() {
    }

    public PaqueteProducto(Producto producto, Paquete paquete) {
       this.producto = producto;
       this.paquete = paquete;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="producto")
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="paquete")
    public Paquete getPaquete() {
        return this.paquete;
    }
    
    public void setPaquete(Paquete paquete) {
        this.paquete = paquete;
    }




}


