package com.marketour.domain;
// Generated 20/04/2015 12:40:07 PM by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paquete generated by hbm2java
 */
@Entity
@Table(name="Paquete"
    ,catalog="devfloor_marketour"
)
public class Paquete  implements java.io.Serializable {


     private Integer id;
     private Proveedor proveedor;
     private Promocion promocion;
     private String nombre;
     private String descripcion;
     private BigDecimal valor;
     private Integer visitas;
     private int estado;
     private Set<ItemCompra> itemCompras = new HashSet<ItemCompra>(0);
     private Set<PaqueteProducto> paqueteProductos = new HashSet<PaqueteProducto>(0);

    public Paquete() {
    }

	
    public Paquete(Proveedor proveedor, String nombre, BigDecimal valor, int estado) {
        this.proveedor = proveedor;
        this.nombre = nombre;
        this.valor = valor;
        this.estado = estado;
    }
    public Paquete(Proveedor proveedor, Promocion promocion, String nombre, String descripcion, BigDecimal valor, Integer visitas, int estado, Set<ItemCompra> itemCompras, Set<PaqueteProducto> paqueteProductos) {
       this.proveedor = proveedor;
       this.promocion = promocion;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.valor = valor;
       this.visitas = visitas;
       this.estado = estado;
       this.itemCompras = itemCompras;
       this.paqueteProductos = paqueteProductos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedor", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="promocion")
    public Promocion getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="valor", nullable=false, precision=10)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    
    @Column(name="visitas")
    public Integer getVisitas() {
        return this.visitas;
    }
    
    public void setVisitas(Integer visitas) {
        this.visitas = visitas;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paquete")
    public Set<ItemCompra> getItemCompras() {
        return this.itemCompras;
    }
    
    public void setItemCompras(Set<ItemCompra> itemCompras) {
        this.itemCompras = itemCompras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paquete")
    public Set<PaqueteProducto> getPaqueteProductos() {
        return this.paqueteProductos;
    }
    
    public void setPaqueteProductos(Set<PaqueteProducto> paqueteProductos) {
        this.paqueteProductos = paqueteProductos;
    }




}


