package com.marketour.domain;
// Generated 13/04/2015 12:03:59 AM by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Paquete generated by hbm2java
 */
@Entity
@Table(name="Paquete"
    ,catalog="grupocre_marketour"
)
public class Paquete  implements java.io.Serializable {


     private Integer id;
     private int proveedor;
     private String nombre;
     private String descripcion;
     private BigDecimal valor;
     private Integer visitas;
     private int estado;

    public Paquete() {
    }

	
    public Paquete(int proveedor, String nombre, BigDecimal valor, int estado) {
        this.proveedor = proveedor;
        this.nombre = nombre;
        this.valor = valor;
        this.estado = estado;
    }
    public Paquete(int proveedor, String nombre, String descripcion, BigDecimal valor, Integer visitas, int estado) {
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.valor = valor;
       this.visitas = visitas;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="proveedor", nullable=false)
    public int getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(int proveedor) {
        this.proveedor = proveedor;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="valor", nullable=false, precision=10)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    
    @Column(name="visitas")
    public Integer getVisitas() {
        return this.visitas;
    }
    
    public void setVisitas(Integer visitas) {
        this.visitas = visitas;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


