package com.marketour.domain;

// Generated 2/05/2015 08:24:36 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PlanAlimentacion generated by hbm2java
 */
@Entity
@Table(name = "PlanAlimentacion", catalog = "devfloor_marketour")
public class PlanAlimentacion implements java.io.Serializable {

	private Integer id;
	private String descripcion;
	private int estado;
	private Set<Alimentacion> alimentacions = new HashSet<Alimentacion>(0);

	public PlanAlimentacion() {
	}

	public PlanAlimentacion(int estado) {
		this.estado = estado;
	}

	public PlanAlimentacion(String descripcion, int estado,
			Set<Alimentacion> alimentacions) {
		this.descripcion = descripcion;
		this.estado = estado;
		this.alimentacions = alimentacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planAlimentacion")
	public Set<Alimentacion> getAlimentacions() {
		return this.alimentacions;
	}

	public void setAlimentacions(Set<Alimentacion> alimentacions) {
		this.alimentacions = alimentacions;
	}

}
