package com.marketour.domain;

// Generated 4/04/2015 03:32:21 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "Producto", catalog = "grupocre_marketour")
public class Producto implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String descripcion;
	private String ubicacion;
	private BigDecimal valor;
	private Integer visitas;
	private Integer compartido;
	private Integer idMoneda;
	private Integer idPromocion;

	public Producto() {
	}

	public Producto(String nombre, String descripcion, String ubicacion,
			BigDecimal valor, Integer visitas, Integer compartido,
			Integer idMoneda, Integer idPromocion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.ubicacion = ubicacion;
		this.valor = valor;
		this.visitas = visitas;
		this.compartido = compartido;
		this.idMoneda = idMoneda;
		this.idPromocion = idPromocion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ubicacion", length = 50)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "valor", precision = 10)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "visitas")
	public Integer getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Integer visitas) {
		this.visitas = visitas;
	}

	@Column(name = "compartido")
	public Integer getCompartido() {
		return this.compartido;
	}

	public void setCompartido(Integer compartido) {
		this.compartido = compartido;
	}

	@Column(name = "idMoneda")
	public Integer getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(Integer idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "idPromocion")
	public Integer getIdPromocion() {
		return this.idPromocion;
	}

	public void setIdPromocion(Integer idPromocion) {
		this.idPromocion = idPromocion;
	}

}
