package com.marketour.domain;
// Generated 12/04/2015 01:17:24 PM by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="Producto"
    ,catalog="grupocre_marketour"
)
public class Producto  implements java.io.Serializable {


     private Integer id;
     private int proveedor;
     private String nombre;
     private String descripcion;
     private int categoria;
     private BigDecimal valor;
     private Integer visitas;
     private Integer capacidad;
     private Integer ubicacion;
     private String coordenadas;
     private int estado;

    public Producto() {
    }

	
    public Producto(int proveedor, String nombre, int categoria, BigDecimal valor, int estado) {
        this.proveedor = proveedor;
        this.nombre = nombre;
        this.categoria = categoria;
        this.valor = valor;
        this.estado = estado;
    }
    public Producto(int proveedor, String nombre, String descripcion, int categoria, BigDecimal valor, Integer visitas, Integer capacidad, Integer ubicacion, String coordenadas, int estado) {
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.categoria = categoria;
       this.valor = valor;
       this.visitas = visitas;
       this.capacidad = capacidad;
       this.ubicacion = ubicacion;
       this.coordenadas = coordenadas;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="proveedor", nullable=false)
    public int getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(int proveedor) {
        this.proveedor = proveedor;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="categoria", nullable=false)
    public int getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(int categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="valor", nullable=false, precision=10)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    
    @Column(name="visitas")
    public Integer getVisitas() {
        return this.visitas;
    }
    
    public void setVisitas(Integer visitas) {
        this.visitas = visitas;
    }

    
    @Column(name="capacidad")
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }

    
    @Column(name="ubicacion")
    public Integer getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Integer ubicacion) {
        this.ubicacion = ubicacion;
    }

    
    @Column(name="coordenadas", length=50)
    public String getCoordenadas() {
        return this.coordenadas;
    }
    
    public void setCoordenadas(String coordenadas) {
        this.coordenadas = coordenadas;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


