package com.marketour.domain;
// Generated 21/04/2015 08:03:17 PM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promocion generated by hbm2java
 */
@Entity
@Table(name="Promocion"
    ,catalog="devfloor_marketour"
)
public class Promocion  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private String condiciones;
     private long descuento;
     private String codigo;
     private int estado;
     private Set<Paquete> paquetes = new HashSet<Paquete>(0);

    public Promocion() {
    }

	
    public Promocion(long descuento, int estado) {
        this.descuento = descuento;
        this.estado = estado;
    }
    public Promocion(String descripcion, Date fechaInicio, Date fechaFin, String condiciones, long descuento, String codigo, int estado, Set<Paquete> paquetes) {
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.condiciones = condiciones;
       this.descuento = descuento;
       this.codigo = codigo;
       this.estado = estado;
       this.paquetes = paquetes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaInicio", length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaFin", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="condiciones")
    public String getCondiciones() {
        return this.condiciones;
    }
    
    public void setCondiciones(String condiciones) {
        this.condiciones = condiciones;
    }

    
    @Column(name="descuento", nullable=false, precision=10, scale=0)
    public long getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(long descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="codigo", length=50)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="promocion")
    public Set<Paquete> getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Set<Paquete> paquetes) {
        this.paquetes = paquetes;
    }




}


