package com.marketour.domain;

// Generated 4/04/2015 03:32:21 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promocion generated by hbm2java
 */
@Entity
@Table(name = "Promocion", catalog = "grupocre_marketour")
public class Promocion implements java.io.Serializable {

	private Integer id;
	private Date fechaInicio;
	private Date fechaFin;
	private BigDecimal descuento;
	private String condiciones;

	public Promocion() {
	}

	public Promocion(Date fechaInicio, Date fechaFin, BigDecimal descuento,
			String condiciones) {
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.descuento = descuento;
		this.condiciones = condiciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaInicio", length = 10)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaFin", length = 10)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "descuento", precision = 10)
	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	@Column(name = "condiciones", length = 50)
	public String getCondiciones() {
		return this.condiciones;
	}

	public void setCondiciones(String condiciones) {
		this.condiciones = condiciones;
	}

}
