package com.marketour.domain;
// Generated 12/04/2015 01:17:24 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="Proveedor"
    ,catalog="grupocre_marketour"
)
public class Proveedor  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private String nit;
     private String cuenta;

    public Proveedor() {
    }

	
    public Proveedor(int id) {
        this.id = id;
    }
    public Proveedor(int id, String descripcion, String nit, String cuenta) {
       this.id = id;
       this.descripcion = descripcion;
       this.nit = nit;
       this.cuenta = cuenta;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="nit", length=50)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="cuenta", length=50)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }




}


