package com.marketour.domain;
// Generated 2/05/2015 08:24:36 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="Proveedor"
    ,catalog="devfloor_marketour"
)
public class Proveedor  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String descripcion;
     private String nit;
     private String cuenta;
     private Set<Paquete> paquetes = new HashSet<Paquete>(0);
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Proveedor() {
    }

	
    public Proveedor(Usuario usuario) {
        this.usuario = usuario;
    }
    public Proveedor(Usuario usuario, String descripcion, String nit, String cuenta, Set<Paquete> paquetes, Set<Producto> productos) {
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.nit = nit;
       this.cuenta = cuenta;
       this.paquetes = paquetes;
       this.productos = productos;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="usuario"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="nit", length=50)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="cuenta", length=50)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Paquete> getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Set<Paquete> paquetes) {
        this.paquetes = paquetes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


