package com.marketour.domain;

// Generated 7/04/2015 12:31:43 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProveedorPublicacion generated by hbm2java
 */
@Entity
@Table(name = "ProveedorPublicacion", catalog = "grupocre_marketour")
public class ProveedorPublicacion implements java.io.Serializable {

	private Integer id;
	private Integer idProveedor;
	private Integer idPublicacion;

	public ProveedorPublicacion() {
	}

	public ProveedorPublicacion(Integer idProveedor, Integer idPublicacion) {
		this.idProveedor = idProveedor;
		this.idPublicacion = idPublicacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "idProveedor")
	public Integer getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Integer idProveedor) {
		this.idProveedor = idProveedor;
	}

	@Column(name = "idPublicacion")
	public Integer getIdPublicacion() {
		return this.idPublicacion;
	}

	public void setIdPublicacion(Integer idPublicacion) {
		this.idPublicacion = idPublicacion;
	}

}
