package com.marketour.domain;
// Generated 13/04/2015 12:03:59 AM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pse generated by hbm2java
 */
@Entity
@Table(name="PSE"
    ,catalog="grupocre_marketour"
)
public class Pse  implements java.io.Serializable {


     private int id;
     private String url;

    public Pse() {
    }

	
    public Pse(int id) {
        this.id = id;
    }
    public Pse(int id, String url) {
       this.id = id;
       this.url = url;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="url")
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


