package com.marketour.domain;

// Generated 4/04/2015 03:32:21 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PublicacionProducto generated by hbm2java
 */
@Entity
@Table(name = "PublicacionProducto", catalog = "grupocre_marketour")
public class PublicacionProducto implements java.io.Serializable {

	private Integer id;
	private Integer idPublicacion;
	private Integer idProducto;

	public PublicacionProducto() {
	}

	public PublicacionProducto(Integer idPublicacion, Integer idProducto) {
		this.idPublicacion = idPublicacion;
		this.idProducto = idProducto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "idPublicacion")
	public Integer getIdPublicacion() {
		return this.idPublicacion;
	}

	public void setIdPublicacion(Integer idPublicacion) {
		this.idPublicacion = idPublicacion;
	}

	@Column(name = "idProducto")
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

}
