package com.marketour.domain;

// Generated 4/04/2015 03:32:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publicacion generated by hbm2java
 */
@Entity
@Table(name = "Publicacion", catalog = "grupocre_marketour")
public class Publicacion implements java.io.Serializable {

	private Integer id;
	private String titulo;
	private String descripcion;
	private String contenido;
	private Date fechaPublicacion;
	private Integer idTipoContenido;

	public Publicacion() {
	}

	public Publicacion(String titulo, String descripcion, String contenido,
			Date fechaPublicacion, Integer idTipoContenido) {
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.contenido = contenido;
		this.fechaPublicacion = fechaPublicacion;
		this.idTipoContenido = idTipoContenido;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "titulo", length = 50)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "contenido", length = 1024)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaPublicacion", length = 10)
	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	@Column(name = "idTipoContenido")
	public Integer getIdTipoContenido() {
		return this.idTipoContenido;
	}

	public void setIdTipoContenido(Integer idTipoContenido) {
		this.idTipoContenido = idTipoContenido;
	}

}
