package com.marketour.domain;

// Generated 7/04/2015 12:31:43 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RedesUsuario generated by hbm2java
 */
@Entity
@Table(name = "RedesUsuario", catalog = "grupocre_marketour")
public class RedesUsuario implements java.io.Serializable {

	private Integer id;
	private Integer idUsuario;
	private Integer idRedSocial;
	private String descripcion;
	private String seguridad;

	public RedesUsuario() {
	}

	public RedesUsuario(Integer idUsuario, Integer idRedSocial,
			String descripcion, String seguridad) {
		this.idUsuario = idUsuario;
		this.idRedSocial = idRedSocial;
		this.descripcion = descripcion;
		this.seguridad = seguridad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "idUsuario")
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "idRedSocial")
	public Integer getIdRedSocial() {
		return this.idRedSocial;
	}

	public void setIdRedSocial(Integer idRedSocial) {
		this.idRedSocial = idRedSocial;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "seguridad", length = 50)
	public String getSeguridad() {
		return this.seguridad;
	}

	public void setSeguridad(String seguridad) {
		this.seguridad = seguridad;
	}

}
