package com.marketour.domain;
// Generated 12/04/2015 01:17:24 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TarjetaCredito generated by hbm2java
 */
@Entity
@Table(name="TarjetaCredito"
    ,catalog="grupocre_marketour"
)
public class TarjetaCredito  implements java.io.Serializable {


     private int id;
     private String numero;
     private String nombre;
     private String codigo;
     private String vencimiento;

    public TarjetaCredito() {
    }

	
    public TarjetaCredito(int id) {
        this.id = id;
    }
    public TarjetaCredito(int id, String numero, String nombre, String codigo, String vencimiento) {
       this.id = id;
       this.numero = numero;
       this.nombre = nombre;
       this.codigo = codigo;
       this.vencimiento = vencimiento;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="numero", length=50)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="nombre", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="codigo", length=50)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="vencimiento", length=50)
    public String getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(String vencimiento) {
        this.vencimiento = vencimiento;
    }




}


