package com.marketour.business;
// Generated 21/04/2015 08:03:17 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TarjetaCredito generated by hbm2java
 */
@Entity
@Table(name="TarjetaCredito"
    ,catalog="devfloor_marketour"
)
public class TarjetaCredito  implements java.io.Serializable {


     private int id;
     private MedioPago medioPago;
     private String numero;
     private String nombre;
     private String codigo;
     private String vencimiento;

    public TarjetaCredito() {
    }

	
    public TarjetaCredito(MedioPago medioPago) {
        this.medioPago = medioPago;
    }
    public TarjetaCredito(MedioPago medioPago, String numero, String nombre, String codigo, String vencimiento) {
       this.medioPago = medioPago;
       this.numero = numero;
       this.nombre = nombre;
       this.codigo = codigo;
       this.vencimiento = vencimiento;
    }
   
  
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    public MedioPago getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(MedioPago medioPago) {
        this.medioPago = medioPago;
    }

    

    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
  
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    

    public String getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(String vencimiento) {
        this.vencimiento = vencimiento;
    }




}


